branch-defaults:
  master:
    environment: onTimer-server-dev
    group_suffix: null
environment-defaults:
  onTimer-server-dev:
    branch: null
    repository: null
global:
  application_name: onTimer_server
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 17.12.1-ce
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
